[theme]
base = "dark"
#primaryColor = "#007bfc"
backgroundColor = "#0c0c0c"
secondaryBackgroundColor = "#141414"
#textColor = "#e6debe"
showSidebarBorder=true
#font = "Inter"
#baseFontWeight = 300
#headingFontWeights = 300

#[theme.sidebar]
#headingFontWeights = "300"
#font = "sans-serif" 
#headingFont = "sans-serif"
#fontSize="9px"
#fontWeight="900"
#baseFontWeight = "light"